name: planqk-quantum
channels:
  - conda-forge
  - quantum-engineering
dependencies:
  - python=3.9
  - pip>=21.1.3
  - pydantic==2.5.0
  - pip:
      ## dev dependencies
      - qiskit==1.0.2
      - qiskit-ibm-runtime==0.21.2
      - qiskit-ibm-provider==0.10.0
      - setuptools
      - pytest
      - pytest-cov
      - pytest-asyncio
      - busypie
      - retrying
      - python-dotenv
      ## prod dependencies
      - requests
      # aws braket
      - amazon-braket-default-simulator==1.21.0
      - amazon-braket-schemas==1.21.0
      # we need the latest dev version as this fixes the issue with the Rigetti's qubit ids
      - git+https://github.com/qiskit-community/qiskit-braket-provider.git@main
      # azure quantum
      - azure-quantum[qiskit]==2.0.0
      - qiskit-ionq==0.5.0
      # dwave
      - dwave-ocean-sdk==6.9.0
