name: planqk-quantum
channels:
  - conda-forge
  - quantum-engineering
dependencies:
  - python=3.9
  - pip>=21.1.3
  - pydantic
  - pip:
      # dev dependencies
      - qiskit
      - qiskit-ibm-runtime
      - setuptools
      - pytest
      - pytest-cov
      - pytest-asyncio
      - busypie
      - retrying
      - python-dotenv
      # prod dependencies
      - requests==2.*
        ## aws braket
      #we need the latest dev version as this fixes the issue with the Rigetti's qubit ids
      - git+https://github.com/qiskit-community/qiskit-braket-provider.git@main
      ## azure quantum
      - azure-quantum[qiskit]
      - qiskit-ionq
      ## dwave
      - dwave-ocean-sdk==6.4.1
