name: planqk-quantum
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.1.3
  - numpy>=1.21.0
  - pip:
      - qiskit-aer>=0.9.1
      - qiskit-terra>=0.18.0
      - requests
      - pytest
      - pytest-cov
