name: planqk-quantum
channels:
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.1.3
  - numpy>=1.23.5
  - pytest>=6.2.4
  - pytest-asyncio>=0.15.0
  - pip:
      - azure-quantum[qiskit]
      - msrest~=0.7.1
      - requests~=2.28.1
      - pytest
      - pytest-cov
      - matplotlib
      - pytest~=7.2.0
      - busypie~=0.5.1
      - responses~=0.22.0
      - setuptools~=65.5.0
