name: planqk-quantum
channels:
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.1.3
  - numpy>=1.21.0
  - pytest>=6.2.4
  - pytest-asyncio>=0.15.0
  - numpy>=1.21.0
  - pip:
      - azure-quantum[qiskit]
      - requests
      - pytest
      - pytest-cov
