name: planqk-quantum
channels:
  - conda-forge
  - quantum-engineering
dependencies:
  - python=3.9
  - pip>=21.1.3
  - pip:
      # dev dependencies
      - setuptools
      - pytest
      - pytest-cov
      - pytest-asyncio
      - busypie
      - responses
      - retrying
      - python-dotenv
      # prod dependencies
      - requests==2.*
      - qiskit-qasm3-import==0.2.0
      ## aws braket
      - amazon-braket-sdk==1.33.0
      - qiskit_braket_provider==0.0.4
      ## azure quantum
      - azure-quantum==0.24.208024
      - qiskit-ionq==0.1.4
