name: planqk-quantum
channels:
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.1.3
  - pytest>=6.2.4
  - pytest-asyncio>=0.15.0
  - pip:
      - azure-quantum==0.24.208024
      - qiskit-ionq==0.1.4
      - qiskit-terra>=0.19.1
      - requests==2.*
      - pytest
      - pytest-cov
      - matplotlib
      - pytest~=7.2.0
      - busypie~=0.5.1
      - responses~=0.22.0
      - setuptools~=65.5.0
      - certifi>=2021.5.30
      - qiskit-aer>=0.10.2
      - qiskit-terra>=0.19.2
      - qiskit-qasm3-import>=0.2.0
      - amazon-braket-sdk==1.33.0
      - python-dotenv>=1.0.0
      - qiskit_braket_provider==0.4.0
      - retrying==1.3.3
      - setuptools>=40.1.0
      - numpy>=1.3
