BACKEND_ID_AWS_SV1 = "aws.sim.sv1"
BACKEND_ID_AWS_DM1 = "aws.sim.dm1"
BACKEND_ID_AWS_IONQ_HARMONY = "aws.ionq.harmony"
BACKEND_ID_AWS_IONQ_ARIA = "aws.ionq.aria"
BACKEND_ID_AWS_IONQ_ARIA_2 = "aws.ionq.aria-2"
BACKEND_ID_AWS_RIGETTI_ASPEN = "aws.rigetti.aspen"
BACKEND_ID_AWS_OQC_LUCY = "aws.oqc.lucy"
BACKEND_ID_AZURE_IONQ_HARMONY = "azure.ionq.harmony"
BACKEND_ID_AZURE_IONQ_SIM = "azure.ionq.simulator"
BACKEND_ID_IBM_NAIROBI = "ibm.q.nairobi"
BACKEND_ID_IBM_LAGOS = "ibm.q.lagos"
BACKEND_ID_IBM_QASM_SIM = "ibm.q.sim.qasm"
BACKEND_ID_IBM_CLOUD_BRISBANE = "ibm.cloud.brisbane"
BACKEND_ID_IBM_CLOUD_CUSCO = "ibm.cloud.cusco"
BACKEND_ID_IBM_CLOUD_KYIV = "ibm.cloud.kyiv"
BACKEND_ID_IBM_CLOUD_NAZCA = "ibm.cloud.nazca"
BACKEND_ID_IBM_CLOUD_SHERBROOKE = "ibm.cloud.sherbrooke"

SUPPORTED_BACKENDS = {BACKEND_ID_AWS_SV1, BACKEND_ID_AWS_DM1, BACKEND_ID_AWS_IONQ_HARMONY, BACKEND_ID_AWS_IONQ_ARIA,
                      BACKEND_ID_AWS_IONQ_ARIA_2, BACKEND_ID_AWS_RIGETTI_ASPEN, BACKEND_ID_AZURE_IONQ_HARMONY,
                      BACKEND_ID_AZURE_IONQ_SIM,
                      BACKEND_ID_IBM_NAIROBI, BACKEND_ID_IBM_LAGOS, BACKEND_ID_IBM_QASM_SIM,
                      BACKEND_ID_IBM_CLOUD_BRISBANE, BACKEND_ID_IBM_CLOUD_CUSCO, BACKEND_ID_IBM_CLOUD_KYIV,
                      BACKEND_ID_IBM_CLOUD_SHERBROOKE}
